# This file needs to exist so that the build can find the BUILD.tpl and
# CROSSTOOL.tpl files.
package(default_visibility = ["//visibility:public"])

# To make bazel query happy.
exports_files([
    "CROSSTOOL.tpl",
    "BUILD.tpl",
])
