#ifndef GBUFFER_H
#define GBUFFER_H

#define SCENE_CONSTANTS_REGISTER             0 // b0
#define LIGHT_CONSTANTS_REGISTER             1 // t1
#define MATERIAL_ALBEDO_TEXTURE_REGISTER     0 // t0
#define MATERIAL_ROUGHNESS_TEXTURE_REGISTER  1 // t1
#define MATERIAL_METALNESS_TEXTURE_REGISTER  2 // t2
#define MATERIAL_NORMAL_MAP_TEXTURE_REGISTER 3 // t3
#define MATERIAL_AMB_OCC_TEXTURE_REGISTER    4 // t4
#define MATERIAL_HEIGHT_TEXTURE_REGISTER     5 // t5
#define MATERIAL_IBL_TEXTURE_REGISTER        6 // t6
#define MATERIAL_ENV_TEXTURE_REGISTER        7 // t7
#define MATERILA_CLAMPED_SAMPLER_REGISTER    8 // s8
#define MODEL_CONSTANTS_REGISTER             0 // b0

#define GBUFFER_RT0_REGISTER     0
#define GBUFFER_RT1_REGISTER     1
#define GBUFFER_RT2_REGISTER     2
#define GBUFFER_RT3_REGISTER     3
#define GBUFFER_ENV_REGISTER     6
#define GBUFFER_IBL_REGISTER     7
#define GBUFFER_SAMPLER_REGISTER 8

#define GBUFFER_POSITION     0
#define GBUFFER_NORMAL       1
#define GBUFFER_ALBEDO       2
#define GBUFFER_F0           3
#define GBUFFER_ROUGHNESS    4
#define GBUFFER_METALNESS    5
#define GBUFFER_AMB_OCC      6
#define GBUFFER_IBL_STRENGTH 7
#define GBUFFER_ENV_STRENGTH 8

#endif // GBUFFER_H
