name: Windows build

on:
  pull_request:

permissions: read-all

jobs:
  windows-build:
    name: Build and run unit tests on Windows
    runs-on: "windows-2019"
    steps:
      - name: Setup Vulkan SDK
        run: |
          Start-BitsTransfer -Source https://sdk.lunarg.com/sdk/download/1.3.216.0/windows/VulkanSDK-1.3.216.0-Installer.exe
          .\VulkanSDK-1.3.216.0-Installer.exe install --accept-licenses --default-answer --confirm-command --root "$HOME\vulkan-sdk"
          "VULKAN_SDK=${HOME}\vulkan-sdk" >> $env:GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Switch to pull request branch and clone submodules
        run: |
          git checkout ${GITHUB_SHA}
          git submodule update --init --recursive
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_TESTS=ON ..
          cmake --build . --target ALL_BUILD --config Release -- /nologo /verbosity:minimal /maxcpucount
      - name: Run unit tests
        run: |
          cd build
          cmake --build . --target RUN_TESTS --config Release -- /nologo /verbosity:minimal /maxcpucount
